### ISSUE TITLE
Indexing batplant.org by GloBI

### ISSUE THREAD

**Issue by jhpoelen** [Eco-Interactions/BatBase#5]
Hi! 

I was wondering whether you'd be open to letting your database by indexed by https://globalbioticinteractions.org as part of a drive to get bat data easier to access via a biodiversity  initiative https://cetaf.org/covid19-taf-communities-taking-action . If you are open to being indexed, batplants.org would be attributed as a dataset along with the original literature reference. 

Also see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/340 .

**Comment by rnbwspctrm** [comment]
Hi! We are very excited about this! I do not see a contact email for you. How can we get in touch directly?

**Comment by jhpoelen** [comment]
For direct contact, please see author email of  https://doi.org/10.1016/j.ecoinf.2014.08.005 . Am looking forward to hearing from you and your collaborators.

**Comment by jhpoelen** [comment]
@rnbwspctrm Note that I got an email from your colleague @seemlesstaylor . Perhaps we can organize a get-together ?
